death_image='files\\images\\ded.png'
room1_image='files\\images\\room1_image.png'
open_door='files\\images\\open_door.png'
hall_image_middle='files\\images\\hall_image.png'
hall_image_left='files\\images\\hallL_image.png'
hall_image_right='files\\images\\hallR_image.png'
westhall_image='files\\images\\westhall_image.png'
easthall_monster_image='files\\images\\easthall_monster_image.png'
easthall_image='files\\images\\easthall_image.png'
easthall_torch_image='files\\images\\easthall_torch_image.png'
basement_image='files\\images\\basement_image.png'

health_bar_0='files\\images\\no_health.png'
health_bar_1='files\\images\\one_health.png'                
health_bar_2='files\\images\\two_health.png'
health_bar_3='files\\images\\three_health.png'                
health_bar_4='files\\images\\four_health.png'
health_bar_5='files\\images\\full_health.png'
health_bar_6='files\\images\\six_health.png'
                
random_descrip1_file='files\\notepad_files\\random_descrip1.txt'
random_descrip1=open(random_descrip1_file,'r').read()
random_descrip2_file='files\\notepad_files\\random_descrip2.txt'
random_descrip2=open(random_descrip2_file,'r').read()
random_descrip3_file='files\\notepad_files\\random_descrip3.txt'
random_descrip3=open(random_descrip3_file,'r').read()
random_descrip4_file='files\\notepad_files\\random_descrip4.txt'
random_descrip4=open(random_descrip4_file,'r').read()
random_descrip5_file='files\\notepad_files\\random_descrip5.txt'
random_descrip5=open(random_descrip5_file,'r').read()
instructions_file='files\\notepad_files\\instructions.txt'
instructions=open(instructions_file,'r').read()
start_room_text_file='files\\notepad_files\\Text_File_1.txt'
start_room_text=open(start_room_text_file,'r').read()
start_look_around_file='files\\notepad_files\\text file 2.txt'
start_look_around_text=open(start_look_around_file,'r').read()
check_bed_file='files\\notepad_files\\Check bed.txt'
check_bed_text=open(check_bed_file,'r').read()
check_box_file='files\\notepad_files\\check box.txt'
check_box=open(check_box_file,'r').read()
check_door_file='files\\notepad_files\\check door.txt'
check_door=open(check_door_file,'r').read()
check_note_file='files\\notepad_files\\check note.txt'
check_note=open(check_note_file,'r').read()
check_pants_file='files\\notepad_files\\check pants.txt'
check_pants_text=open(check_pants_file,'r').read()
check_window_file='files\\notepad_files\\check window.txt'
check_window=open(check_window_file,'r').read()
check_floor_file='files\\notepad_files\\check_floor.txt'
check_floor=open(check_floor_file,'r').read()
open_door1_file='files\\notepad_files\\open_door1.txt'
open_door1=open(open_door1_file,'r').read()
hallway_file='files\\notepad_files\\hallway.txt'
hallway=open(hallway_file,'r').read()
hallwayL_file='files\\notepad_files\\hallwayL.txt'
hallwayL=open(hallwayL_file,'r').read()
hallwayR_file='files\\notepad_files\\hallwayR.txt'
hallwayR=open(hallwayR_file,'r').read()
right_hall_file='files\\notepad_files\\right hall.txt'
right_hall=open(right_hall_file,'r').read()
check_monster_file='files\\notepad_files\\check_monster.txt'
check_monster=open(check_monster_file,'r').read()
normal_hit_file='files\\notepad_files\\normal monster hit.txt'
normal_hit=open(normal_hit_file,'r').read()
run_alcove_file='files\\notepad_files\\run_alcove.txt'
run_alcove=open(run_alcove_file,'r').read()
sad_hit_file='files\\notepad_files\\monster sadly runs.txt'
sad_hit=open(sad_hit_file,'r').read()
monster_jewel_file='files\\notepad_files\\monster jewel.txt'
monster_jewel=open(monster_jewel_file,'r').read()
monster_encounter_file='files\\notepad_files\\monster encounter.txt'
monster_encounter=open(monster_encounter_file,'r').read()
hug_monster_file='files\\notepad_files\\hug monster.txt'
hug_monster=open(hug_monster_file,'r').read()
fuck_monster_file='files\\notepad_files\\fuck monster.txt'
fuck_monster=open(fuck_monster_file,'r').read()
guard_convo_1_file='files\\notepad_files\\guard convo 1.txt'
guard_convo_1=open(guard_convo_1_file,'r').read()
give_gem_file='files\\notepad_files\\give jewel.txt'
give_gem=open(give_gem_file,'r').read()
empty_6_turned_file='files\\notepad_files\\empty hall 4.5.txt'
empty_6_turned=open(empty_6_turned_file,'r').read()
empty_6_waited_file='files\\notepad_files\\empty hall 4.5 (waited).txt'
empty_6_waited=open(empty_6_waited_file,'r')
empty_hall_notorch_file='files\\notepad_files\\empty_hall_notorch.txt'
empty_hall_notorch=open(empty_hall_notorch_file,'r').read()
deny_jewel_file='files\\notepad_files\\deny jewel.txt'
deny_jewel=open(deny_jewel_file,'r').read()
alcove_file='files\\notepad_files\\alcove.txt'
alcove=open(alcove_file,'r').read()
check_alcove_notorch_file='files\\notepad_files\\check_alcove_notorch.txt'
check_alcove_notorch=open(check_alcove_notorch_file,'r').read()
check_alcove_torch_file='files\\notepad_files\\check_alcove_torch.txt'
check_alcove_torch=open(check_alcove_torch_file,'r').read()
check_skeleton_file='files\\notepad_files\\check_skeleton.txt'
check_skeleton=open(check_skeleton_file,'r').read()
go_alcove_torch_file='files\\notepad_files\\go_alcove_torch.txt'
go_alcove_torch=open(go_alcove_torch_file,'r').read()
go_alcove_notorch_file='files\\notepad_files\\go_alcove_notorch.txt'
go_alcove_notorch=open(go_alcove_notorch_file,'r').read()
left_hall_file='files\\notepad_files\\left hall.txt'
left_hall=open(left_hall_file,'r').read()
left_hall_look_file='files\\notepad_files\\left hall look around.txt'
left_hall_look=open(left_hall_look_file,'r').read()
left_hall_look_nosound_file='files\\notepad_files\\left hall look nosound.txt'
left_hall_look_nosound=open(left_hall_look_nosound_file,'r').read()
left_hall_nosound_file='files\\notepad_files\\left hall no sound.txt'
left_hall_nosound=open(left_hall_nosound_file,'r').read()
check_sound_file='files\\notepad_files\\check_sound.txt'
check_sound=open(check_sound_file,'r').read()
westhall_check_wall_file='files\\notepad_files\\westhall_check_wall.txt'
westhall_check_wall=open(westhall_check_wall_file,'r').read()
shadow_response_file='files\\notepad_files\\shadow response.txt'
shadow_response=open(shadow_response_file,'r').read()
shadow_yes_file='files\\notepad_files\\shadow_yes.txt'
shadow_yes=open(shadow_yes_file,'r').read()
shadow_no_file='files\\notepad_files\\shadow_no.txt'
shadow_no=open(shadow_no_file,'r').read()
get_jewel_file='files\\notepad_files\\get_jewel.txt'
get_jewel=open(get_jewel_file,'r').read()
get_health_file='files\\notepad_files\\get_health.txt'
get_health=open(get_health_file,'r').read()
sewer_file='files\\notepad_files\\sewer.txt'
sewer_go=open(sewer_file,'r').read()
sewer_look_file='files\\notepad_files\\sewer 2.txt'
sewer_look=open(sewer_look_file,'r').read()
cultist_conversation_file='files\\notepad_files\\cultist conversation.txt'
cultist_conversation=open(cultist_conversation_file,'r').read()
lockbox_file='files\\notepad_files\\lockbox.txt'
lockbox=open(lockbox_file,'r').read()
check_note_two_file='files\\notepad_files\\note two.txt'
check_note_two=open(check_note_two_file,'r').read()
spider_attack_file='files\\notepad_files\\spider attack.txt'
spider_attack=open(spider_attack_file,'r').read()
sacrifice_file='files\\notepad_files\\sacrifice.txt'
sacrifice=open(sacrifice_file,'r').read()
sacrifice_ending_file='files\\notepad_files\\sacrifice ending.txt'
sacrifice_ending=open(sacrifice_ending_file,'r').read()
river_ride_file='files\\notepad_files\\river_ride.txt'
river_ride=open(river_ride_file,'r').read()
guard_attack_file='files\\notepad_files\\guard attack.txt'
guard_attack=open(guard_attack_file,'r').read()
guard_talk_file='files\\notepad_files\\guard_talk.txt'
guard_talk=open(guard_talk_file,'r').read()
dice_explain_file='files\\notepad_files\\dice_explain.txt'
dice_explain=open(dice_explain_file,'r').read()
guard_room_guard_file='files\\notepad_files\\guard room w guard.txt'
guard_room_guard=open(guard_room_guard_file,'r').read()
guard_room_noguard_file='files\\notepad_files\\guard room no guard.txt'
guard_room_noguard=open(guard_room_noguard_file,'r').read()
guard_river_convo_file='files\\notepad_files\\guard_river_convo.txt'
guard_river_convo=open(guard_river_convo_file,'r').read()
field_file='files\\notepad_files\\field.txt'
field=open(field_file,'r').read()
backhall_w_man_file='files\\notepad_files\\backhall_w_man.txt'
backhall_w_man=open(backhall_w_man_file,'r').read()
backhall_noman_file='files\\notepad_files\\backhall_noman.txt'
backhall_noman=open(backhall_noman_file,'r').read()
man_firsttalk_file='files\\notepad_files\\man_firsttalk.txt'
man_firsttalk=open(man_firsttalk_file,'r').read()
man_talk_uniform_file='files\\notepad_files\\man_talk_uniform.txt'
man_talk_uniform=open(man_talk_uniform_file,'r').read()
big_man_fight_file='files\\notepad_files\\big_man_attack.txt'
big_man_fight=open(big_man_fight_file,'r').read()
exit_choice_file='files\\notepad_files\\exit_choice.txt'
exit_choice=open(exit_choice_file,'r').read()
valley_file='files\\notepad_files\\valley.txt'
valley=open(valley_file,'r').read()
south_exit_file='files\\notepad_files\\south_exit.txt'
south_exit=open(south_exit_file,'r').read()
statue_file='files\\notepad_files\\statue.txt'
statue=open(statue_file,'r').read()
statue_firsteye_file='files\\notepad_files\\statue_firsteye.txt'
statue_firsteye=open(statue_firsteye_file,'r').read()
statue_thirdeye_file='files\\notepad_files\\statue_thirdeye.txt'
statue_thirdeye=open(statue_thirdeye_file,'r').read()
statue_firsttalk_file='files\\notepad_files\\statue_firsttalk.txt'
statue_firsttalk=open(statue_firsttalk_file,'r').read()
riddle1_file='files\\notepad_files\\riddle1.txt'
riddle1=open(riddle1_file,'r').read()
riddle2_file='files\\notepad_files\\riddle2.txt'
riddle2=open(riddle2_file,'r').read()
riddle3_file='files\\notepad_files\\riddle3.txt'
riddle3=open(riddle3_file,'r').read()
riddles_solved_file='files\\notepad_files\\riddles_solved.txt'
riddles_solved=open(riddles_solved_file,'r').read()
treasure_file='files\\notepad_files\\treasure.txt'
treasure=open(treasure_file,'r').read()
